### ISSUE TITLE
sql analysis "filter" type node location is wrong

### ISSUE THREAD

**Issue by cyyeh** [Canner/wren-engine#661]
sql:

```sql
SELECT "oi"."ProductId", "o"."OrderId", "o"."CustomerId" FROM "order_items" AS "oi" JOIN "orders" AS "o" ON "oi"."OrderId" = "o"."OrderId" JOIN "customers" AS "c" ON "o"."CustomerId" = "c"."Id" WHERE "o"."PurchaseTimestamp" >= '2023-01-01' AND "o"."PurchaseTimestamp" < '2024-01-01'
```

json:
```json
"filter": {
  "type": "AND",
  "left": {
    "type": "EXPR",
    "node": "(\"o\".\"PurchaseTimestamp\" >= '2023-01-01')",
    "nodeLocation": {
      "line": 1,
      "column": 225
    }
  },
  "right": {
    "type": "EXPR",
    "node": "(\"o\".\"PurchaseTimestamp\" < '2024-01-01')",
    "nodeLocation": {
      "line": 1,
      "column": 269
    }
  },
  "nodeLocation": {
    "line": 1,
    "column": 201
  }
}
```

nodeLocation of `"(\"o\".\"PurchaseTimestamp\" >= '2023-01-01')"` should be
```json
"nodeLocation": {
  "line": 1,
  "column": 201
}
```

**Comment by goldmedal** [comment]
HI @cyyeh 
I think this result is expected for our parser. Because `(\"o\".\"PurchaseTimestamp\" >= '2023-01-01')` is an `GREAT_EQAUL_EXPRSSION` which position is depended on where is the greater-eq char, I think it makes sense for me. 
The location 201 is for `"o"."PurchaseTimestamp"`. I think we have provided the list of `expr sources` in the latest version. You can find it in `exprSources`.

**Comment by cyyeh** [comment]
> HI @cyyeh I think this result is expected for our parser. Because `(\"o\".\"PurchaseTimestamp\" >= '2023-01-01')` is an `GREAT_EQAUL_EXPRSSION` which position is depended on where is the greater-eq char, I think it makes sense for me. The location 201 is for `"o"."PurchaseTimestamp"`. I think we have provided the list of `expr sources` in the latest version. You can find it in `exprSources`.

cc @andreashimin  @onlyjackfrost
