### ISSUE TITLE
Wren core transform SQL failed `Error during planning: cume_dist does not support zero arguments`

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#924]
```sql
SELECT
    cume_dist() OVER (ORDER BY id) AS cume_dist 
FROM (
    SELECT 1 AS id, 'A' AS category UNION ALL
    SELECT 2 AS id, 'B' AS category UNION ALL
    SELECT 3 AS id, 'A' AS category UNION ALL
    SELECT 4 AS id, 'B' AS category UNION ALL
    SELECT 5 AS id, 'A' AS category
) AS t
```
```
DataFusion error: Error during planning: Error during planning: cume_dist does not support zero arguments. No function matches the given name and argument types 'cume_dist()'. You might need to add explicit type casts.
	Candidate functions:
	cume_dist(Any, .., Any)
```

Also other window functions too.
`dense_rank`, `percent_rank`, `rank`, `row_number`.

BigQuery function reference
https://cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions#cume_dist

**Comment by goldmedal** [comment]
The root cause is that we didn't register the correct function signature for the window function. I think it can be fixed easily by following the same pattern of `ByPassScalarUDF` 
https://github.com/Canner/wren-engine/blob/625b5b4e7028b97d2b0596b7706f8151d6140aee/wren-core/core/src/mdl/function.rs#L73-L77

for `ByPassWindowFunction` and `ByPassAggregateUDF`
https://github.com/Canner/wren-engine/blob/625b5b4e7028b97d2b0596b7706f8151d6140aee/wren-core/core/src/mdl/function.rs#L120

https://github.com/Canner/wren-engine/blob/625b5b4e7028b97d2b0596b7706f8151d6140aee/wren-core/core/src/mdl/function.rs#L161
